import threading
from typing import Any, Callable, Dict, List, Optional, Set

from agent.agent_state import AgentState
from agent.task_system import TaskEngine, ExecutionMode, TaskNode
from memory.memory_store import MemoryStore
from agent.working_memory import WorkingMemory
from agent.context_compressor import ContextCompressor
from tools.code_graph import CodeGraphBuilder
from agent.retriever import Retriever
from agent.attention_manager import AttentionManager
from agent.forgetting import ForgettingManager


class AgentWorkerBase:
    """提供 AgentWorker 及其 Mixin 共享屬性與方法的型別定義基底類別。"""

    available_functions: Dict[str, Callable]
    memory_store: MemoryStore
    working_memory: WorkingMemory
    context_compressor: ContextCompressor
    retriever: Retriever
    attention_manager: AttentionManager
    forgetting_manager: ForgettingManager
    code_graph: CodeGraphBuilder
    engine: TaskEngine
    execution_mode: ExecutionMode

    base_url: str
    api_key: str
    model_name: str
    client: Any
    server_mode: bool
    use_local_llama: bool
    llama_client: Any

    state: AgentState
    current_user_prompt: str
    current_images: list
    history: List[Dict[str, Any]]
    is_paused_for_input: bool
    user_reply_content: str
    max_think_limit: int
    _doc_shown_tools: Set[str]

    _thread: Any
    _stop_event: threading.Event
    _active_stream: Any
    _last_finish_reason: Optional[str]
    event_callback: Optional[Callable]

    def _should_stop(self) -> bool: ...

    def emit(self, event_type: str, payload: Any): ...
    def ask_user(self, question: str) -> str: ...
    def read_tool_doc(self, tool_name: str) -> str: ...
    def request_stop(self): ...
    def is_running(self) -> bool: ...
    def set_user_prompt(self, prompt: str, images: Optional[list] = None): ...
    def _save_history(self): ...
    def _load_history(self) -> List[Dict[str, Any]]: ...
    def maybe_run_forgetting_pass(self): ...
    def _run_inner(self): ...
    def _run_direct_mode(self, initial_content: Optional[str] = None): ...
    def _maybe_compress_history(self): ...
    def _build_user_content(self, text: str, images: Any = None) -> Any: ...
    def _call_llm(self, *args: Any, **kwargs: Any) -> str: ...
    def _call_llm_stream(self, messages: list) -> str: ...
    def _call_and_execute(self, prompt: str) -> str: ...
    def _similar_to_previous_reply(self, text: str) -> bool: ...
    def _parse_structured_fields(self, text: str, field_names: list) -> dict: ...
    def _auto_queue_impact_checks(self, task: TaskNode): ...
    def _parse_tool_arguments(self, func_name: str, args_str: str) -> tuple[list, dict]: ...
    def _judge_and_remember_from_turn(self, user_text: str, assistant_text: str): ...
    def _remember_facts(self, facts: list, source: str = "價值判斷"): ...
    def _parse_memory_facts(self, text: str) -> list: ...
    def _split_reflect_output(self, text: str) -> tuple[str, list]: ...
    def _extract_think_and_action(self, text: str) -> tuple[str, str]: ...
    def _execute_tools(self, content: str) -> tuple[bool, str, str]: ...
    def _execute_tool_call(self, content: str) -> tuple[bool, str, str]: ...

    # Memory methods from AgentMemoryMixin
    def remember(self, id: str, type: str, summary: str = "", properties: Optional[dict] = None) -> str: ...
    def recall(self, id: str) -> str: ...
    def relate(self, source_id: str, rel: str, target_id: str) -> str: ...
    def record_observation(self, id: str, about_id: str, conclusion: str,
                           confidence: float = 0.8, runtime_action: str = "context") -> str: ...
    def recall_observation(self, about_id: str) -> str: ...
    def recall_with_event(self, id: str, event_id: str) -> str: ...
    def recall_related(self, id: str, rel: Optional[str] = None) -> str: ...
    def search_memory(self, keyword: str) -> str: ...
    def build_code_graph(self, filepath: str, module_name: Optional[str] = None) -> str: ...
    def build_code_graph_for_project(self, root_dir: str) -> str: ...
    def find_callers(self, func_id: str) -> str: ...
    def find_callees(self, func_id: str) -> str: ...
